server:
  port: 8000
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id : first-service
          uri: http://localhost:8001/
          predicates:
            - Path=/first-service/**
        - id: second-service
          uri: http://localhost:8002/
          predicates:
            - Path=/second-service/**